spring:
  datasource:
    url: jdbc:h2:mem:squares;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  thymeleaf:
    cache: false
  h2:
    console:
      enabled: true

squares:
  reservationTtlSeconds: 30
  adminToken: admin
  houseOnLock: true
  showPurchaserNames: false

logging:
  level:
    org.hibernate.SQL: warn

tpi:
  base-url: http://localhost:8080/mock-tpi
  currency: USD
  game-type-id: 1073741824
  game-type-variation-id: 1073741824
  third-party-transaction-type-id: 1073741824
  round-to-be-closed: true
